apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "theia.fullname" . }}
  labels:
    {{- include "theia.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
       storage: 2Gi
  storageClassName: longhorn
  volumeMode: Filesystem