apiVersion: v1
kind: Secret
metadata:
    labels:
        {{- include "chart-guilherme.labels" . | nindent 4 }}
    {{- if .Values.secret.name }}
    name: {{ .Values.secret.name }}
    {{- else }}
    name: {{ include "chart-guilherme.fullname" . }}
    {{- end }}
    # Alternativa
    # name: {{ .Values.secret.name | default (include "chart-guilherme.fullname" .) }}
type: Opaque
{{- with .Values }}
    data:
        MONGO_URI: {{ .MONGO_URI | b64enc | quote }}
        USERNAME: {{ .USERNAME | b64enc | quote }}
        PASSWORD: {{ .PASSWORD | b64enc | quote }}
{{- end }}