apiVersion: v2
name: chart-guilherme
description: Chart Guilherme - Aula Cloud Native Setembro/22
type: application
version: 0.1.0
appVersion: "1.16.0"
icon: https://static.wikia.nocookie.net/mtgsalvation_gamepedia/images/7/78/P.svg/revision/latest/scale-to-width-down/357?cb=20160125100609